config/routes.rb
Rails.application.routes.draw do
  
  get 'admin' => 'admins#top'
  resources :admins

  get 'admins/top'
  
  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :courses, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :dinners, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :spaces, only: [:index, :new, :create, :edit, :update, :destroy]

  root 'home#top'
  resources :inquiries do
    resources :answers
  end
  
  get "menu" => "home#menu"
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :inquiry
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :menus
end

app/models/course.rb
class Course < ApplicationRecord
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }
    validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
    
end

app/models/dinner.rb
class Dinner < ApplicationRecord
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }
    validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
    
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    has_many :answers
end

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :category
end

app/models/space.rb
class Space < ApplicationRecord
    
    has_attached_file :image, styles: { medium: "300x300>", thumb: "50x50>" }
    validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
    
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :basic_auth, only: [:top]

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
    
  def top
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new(inquiry_id: params[:inquiry_id])
    @inquiry = Inquiry.find_by(id: params[:inquiry_id])
  end

  def create
    @answer = Answer.new(answer_params)
  
    
    respond_to do |format| 
      if @answer.save
        AnswerMailer.send_when_create(@answer).deliver
        format.html { redirect_to root_path, notice: '回答が保存されました。' }
        format.json { render "home/top", status: :created, location: @answer } 
      else
        format.html { render "home/top" }
        format.json { render json: @answer.errors, status: :unprocessable_entity } 
      end
    end
  end
  
  private 
    def answer_params
      params.require(:answer).permit(:inquiry_id, :answer)
    end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
        @inquiry = Inquiry.new
  end
  
  def menu
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  
  def new
    @inquiry = Inquiry.new
  end
  
  def create
    @inquiry = Inquiry.new(inquiry_params)
    
    respond_to do |format| 
      if @inquiry.save
        InquiryMailer.send_when_create(@inquiry).deliver
        format.html { redirect_to root_path, notice: 'お問合せ保存されました。' }
        format.json { render "home/top", status: :created, location: @inquiry } 
      else
        format.html { render "home/top" }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity } 
      end
    end
    
    
    
    
    
    # if @inquiry.save
    #   flash[:notice] = "#{@inquiry.name}様、お問合せ送信されました"
    #   redirect_to root_path
    # else
    #   flash[:notice] = "お問合せ送信できませんでした"
    #   render 'inquiries/new'      
    # end
  end

  def index
    @inquiries = Inquiry.all.order(created_at: :desc)
  end

  private 
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :phone, :content)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    def index
        @menus = Menu.all
    end
    
    def new
        @menu = Menu.new
    end
    
    def create
        @menu = Menu.new(menu_params)
        if @menu.save
          flash[:notice] = "新メニュー登録されました"
        else
          flash[:notice] = "新メニュー登録できませんでした"
          render "menus/new"      
        end
    end
    
    def edit
        @menu = Menu.find_by(id: params[:id])
    end
    
    def update
        @menu = Menu.find_by(id: params[:id])
        @menu.update(params.require(:menu).permit(:name, :detail, :category_id, :price))
        flash[:notice] = "編集が完了しました"
    end
    
    def destroy
        @menu = Menu.find(params[:id])
        @menu.destroy
    end
    
    private 
    def menu_params
      params.require(:menu).permit(:name, :detail, :category_id, :price)
    end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
    
    def index
        @spaces = Space.all
    end
    
    def new
        @space = Space.new
    end
    
    def create
        @space = Space.new(space_params)
        if @space.save
          flash[:notice] = "スペース写真が登録されました"
        else
          flash[:notice] = "スペース写真を登録できませんでした"
          render "spaces/new"  
        end
    end
    
    def edit
        @space = Space.find_by(id: params[:id])
    end
    
    def update
        @space = Space.find_by(id: params[:id])
        @space.update(params.require(:space).permit(:image))
        flash[:notice] = "編集が完了しました"
    end
    
    def destroy
        @space = Space.find(params[:id])
        @space.destroy
    end
    
    private 
    def space_params
      params.require(:space).permit(:image)
    end    
    
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/dinners_helper.rb
module DinnersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/inquiries/_new.html.erb
<div class="contact-text">
    <p>お問い合せ</p>
</div>
<%= form_for @inquiry do |f| %>
    <div class="contact-form-text">
        <p>お名前</p>
    </div>
    <div class="contact-form-box">
        <%= f.text_field :name %>
    </div>
    <div class="contact-form-text">
        <p>メールアドレス</p>
    </div>
    <div class="contact-form-box">
        <%= f.text_field :email %>
    </div>
    <div class="contact-form-text">
        <p>電話番号</p>
    </div>
    <div class="contact-form-box">
        <%= f.text_field :phone %>
    </div>
    <div class="contact-form-text">
        <p class="ccc">お問い合わせ内容</p>
    </div>
    <div class="contact-form-box2">
    　　<%= f.text_area :content %>
    </div>
    <div class="contact-form-b">
        <%= f.submit "送信する" %>
    </div>
<% end %>

app/views/inquiries/index.html.erb
<h1>Inquiries index</h1>


<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col" style="width: 10%;">名前</th>
      <th scope="col" style="width: 25%;">メール</th>
      <th scope="col" style="width: 15%;">電話</th>
      <th scope="col" style="width: 25%;">内容</th>
      <th scope="col" style="width: 25%;">回答</th>
    </tr>
  </thead>
  <tbody>
    <% @inquiries.each do |i| %>
        <tr>
          <th scope="row"><%= i.name %></th>
          <td><%= i.email %></td>
          <td><%= i.phone %></td>
          <td><%= link_to simple_format(i.content), new_inquiry_answer_path(i.id) %></td>
          <td>
          <% Answer.where(inquiry_id: i.id).each do |answer| %>
            <%= simple_format(answer.answer) %>
            <%= answer.created_at.strftime("%Y-%m-%d %H:%M") %>
          <% end %>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<div class="Inquiries-top">
  <a href="/admin"><button type="button" class="btn btn-success">トップに戻る</button></a>
</div>